spring:
  application:
    name: app
  profiles:
    active: ${APP_ENV:dev}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://a269ee1e968200dbecb719fef5002727@o4510470985547776.ingest.de.sentry.io/4510471040401488
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
  exception-resolver-order: -2147483647